ThePrimeagen/vim-be-good

.editorconfig, README.md, rplugin/node/vim-be-good/game/base.js, rplugin/node/vim-be-good/game/delete.js, rplugin/node/vim-be-good/game/whackamole.js, rplugin/node/vim-be-good/index.js, src/game/base.ts, src/game/types.ts, src/game/whackamole.ts, src/index.ts
@ThePrimeagen I closed the other PR so I could put up two proper feature branches at the same time. This is the same as the other one I closed.
=> Add whackamole

README.md
I did this because I missed the step 2 in the instructions and my vim was not ok with python.
=> make instructions more clear and inform about python requirement.

.eslintrc.js, package-lock.json, package.json, src/game/base.ts, src/game/ci.ts, src/game/delete.ts, src/game/types.ts, src/game/whackamole.ts, src/index.ts, src/log.ts, src/menu.ts, src/repl.ts, src/wait.ts
Adds eslint and prettier to dev deps and fix some linter errors :)
I don't have any strong opinions on linter rules. If you prefer some style i'll gladly add it and update the PR.
=> Add eslint and prettier

README.md
=> feat(pr):s that don't suck

src/index.ts
VimBeGood now creates a scratch buffer and puts it in a floating window for the game
#16
=> added floating window support

.gitignore, README.md, rplugin/node/vim-be-good/game/base.js, rplugin/node/vim-be-good/game/delete.js, rplugin/node/vim-be-good/game/whackamole.js, rplugin/node/vim-be-good/index.js, rplugin/node/vim-be-good/menu.js, src/index.ts
Floating window is now the default, you can turn it off though using let `g:vim_be_good_floating = 0`
=> feat(buffer-window): options for how to open window.

package-lock.json, package.json
Hey dude, it pains me to see you to struggle having to manually rebuild the plugin every time. Hope this helps. Sick streams 🔥
=> Watch mode

rplugin/node/vim-be-good/index.js, src/index.ts
This will fix the clobber buffer bug.
=> fix(blow-your-buffer-away): Sorry

.github/workflows/ci.yaml, package.json, src/game-buffer.ts, src/game/base.ts, src/game/ci-round.ts, src/game/delete-round.ts, src/game/round.ts, src/game/types.ts, src/game/whackamole-round.ts, src/index.ts, src/log.ts, src/menu.ts, src/repl.ts, src/wait.ts
Prettier is in town. Since the amount of people contributing is growing here's a little something that might help. I've added two commands
- `npm run lint` checks if prettier is happy
- `npm run lint:fix` makes prettier happy for the files inside `src` directory (don't care about the post ts js files)
I've also added 2 checks for github actions(prob need to enable them in the repo settings). So if someone makes a PR that breaks the plugin(typescript build really) or the prettier gets upset you'd be the first one to know about it.
The last commit contains all of the prettier stuff. Therefore the interesting bits are in the first two.
Potentially we can also put the `lint:fix` as a precommit hook so no one would ever need to worry about it.
BTW loved the definition of simp developer on a …
=> GitHub actions+prettier

rplugin/node/vim-be-good/game-buffer.js, rplugin/node/vim-be-good/game/base.js, rplugin/node/vim-be-good/game/ci-round.js, rplugin/node/vim-be-good/game/ci.js, rplugin/node/vim-be-good/game/delete-round.js, rplugin/node/vim-be-good/game/delete.js, rplugin/node/vim-be-good/game/hjkl.js, rplugin/node/vim-be-good/game/types.js, rplugin/node/vim-be-good/game/whackamole-round.js, rplugin/node/vim-be-good/index.js, rplugin/node/vim-be-good/log.js, rplugin/node/vim-be-good/menu.js, rplugin/node/vim-be-good/repl.js, rplugin/node/vim-be-good/wait.js, src/game-buffer.ts, src/game/hjkl.ts, src/game/types.ts, src/index.ts, src/repl.ts
This addresses #37 
Unfortunately the bug where round two, #39 is present in all games.  I must fix this!!!
=> feat(hjkl): The hjkl game for those that are new.

.gitignore, rplugin/node/vim-be-good/game-buffer.js, rplugin/node/vim-be-good/game/base.js, rplugin/node/vim-be-good/game/ci-round.js, rplugin/node/vim-be-good/game/delete-round.js, rplugin/node/vim-be-good/game/hjkl.js, rplugin/node/vim-be-good/game/round.js, rplugin/node/vim-be-good/game/whackamole-round.js, rplugin/node/vim-be-good/index.js, src/game-buffer.ts, src/game/base.ts, src/game/ci-round.ts, src/game/delete-round.ts, src/game/hjkl.ts, src/game/round.ts, src/game/whackamole-round.ts, src/index.ts
Round 2 issue along with some incorrect round 1 placed cursors.
=> Rounfd2: And a lot of other issues.

rplugin/node/vim-be-good/index.js, src/index.ts
=> fix(bites): The dust

src/game/base.ts, src/index.ts, src/menu.ts
Added endless mode for noob level difficulty.
The new game difficulty was introduced in #58. I decided that level may also be an endless practice level.
=> Endless mode

README.md
#55 
I hope it is good enough.
=> Added contribute section

src/game/base.ts, src/index.ts
Now you can view your average time during rounds including practice mode.
In practice mode real round count is shown instead of 1 as before.
=> Added in round statistics

src/game/delete-round.ts
Fixed offset for noob difficulty it's not being constantly overwritten anymore.
=> Fix noob offset

src/menu.ts
=> feat(non-noob-start): Easy starting difficulty.

lua/vim-be-good/init.lua, lua/vim-be-good/log.lua
=> PRIME PLZ PLZ PLZ

lua/vim-be-good/game-runner.lua
* fix game type of nil displaying after a completed rounds
* fix round 11/10 to round 10/10 on last screen
* fix double decimal point on time on last screen
=> small bug fixes

lua/vim-be-good/games/ci.lua, lua/vim-be-good/games/whackamole.lua
=> fix(whackamole): Made a space betwixt instructions and game line.

plugin/vim-be-good.vim
=> add neovim version guard

lua/vim-be-good/init.lua, lua/vim-be-good/window.lua
=> feat: add window padding config options

.github/workflows/ci.yaml, lua/vim-be-good/game-runner.lua, lua/vim-be-good/game-utils.lua, lua/vim-be-good/games/words.lua, lua/vim-be-good/types.lua, lua/vim-be-good/window.lua
This will help with beginners trying to have the most basic motions
=> feat: the greatest game for beginners

lua/vim-be-good/games/ci.lua
I scored terribly on this game until I read the source and realized I wasn't supposed to change the conditional, just the predicate.
=> Update ci instructions
